const agencies = [
  {
    name: "СОЛЬ",
    link: "https://solcreative.ru/",
    zodiac: "Телец",
    logo: "agency/sol.png",
    id: "salt",
  },
  {
    name: "Grape",
    link: "https://grape.ru/ru",
    zodiac: "Водолей",
    logo: "agency/grape.svg",
    id: "grape",
  },
  {
    name: "Апрель",
    link: "https://april-agency.com/",
    zodiac: "Овен",
    logo: "agency/aprel.svg",
    id: "april",
  },
  {
    name: "CreativePeople",
    link: "https://cpeople.ru/",
    zodiac: "Стрелец",
    logo: "agency/creativepeople.png",
    id: "creativepeople",
  },
  {
    name: "makelove",
    link: "https://makeloveagency.com/ru",
    zodiac: "Лев",
    logo: "agency/makelove.svg",
    id: "makelove",
  },
  {
    name: "Depot",
    link: "https://www.depotwpf.ru/",
    zodiac: "Дева",
    logo: "agency/depot.svg",
    id: "depot",
  },
  {
    name: "Март",
    link: "https://mart.agency",
    zodiac: "Рыбы",
    logo: "agency/mart.svg",
    id: "mart",
  },
  {
    name: "Hate",
    link: "https://hate.agency/ru/",
    zodiac: "Рак",
    logo: "agency/hate.png",
    id: "hate",
  },
  {
    name: "Sensesay",
    link: "https://sensesay.ru/",
    zodiac: "Близнецы",
    logo: "agency/sense.svg",
    id: "sensesay",
  },
  {
    name: "Rassvet.digital",
    link: "https://rassvet.digital",
    zodiac: "Водолей",
    logo: "agency/rassvet.png",
    id: "rassvetdigital",
  },
  {
    name: "Digital Lab",
    link: "https://digital-lab.ru/",
    zodiac: "Скорпион",
    logo: "agency/diglab.svg",
    id: "digitallab",
  },
  {
    name: "Cats Digital Studio",
    link: "https://www.cats.studio/",
    zodiac: "Близнецы",
    logo: "agency/cats.png",
    id: "cats",
  },
  {
    name: "The Directors",
    link: "https://thedirectors.ru",
    zodiac: "Лев",
    logo: "agency/directors.png",
    id: "thedirectors",
  },
  {
    name: "RODNYA Creative PR Studio",
    link: "https://rodnya.moscow/",
    zodiac: "Весы",
    logo: "agency/rodnya.png",
    id: "rodnya",
  },
];

export default agencies;
