const comps = [
  {
    zodiac: "Овен",
    name: "Stark Industries",
    logo: "comps/stark.svg",
    comment: "Stark Industries («Железный человек»)",
    text: "Есть много вариантов Lorem Ipsum, но большинство из них имеет не всегда приемлемые модификации, например, юмористические вставки или слова, которые даже отдалённо не напоминают латынь. Если вам нужен Lorem Ipsum для серьёзного проекта, вы наверняка не хотите какой-нибудь шутки, скрытой в середине абзаца.",
    id: "starkindustries",
  },
  {
    zodiac: "Телец",
    name: "The Krusty Krab",
    logo: "comps/krusty.svg",
    comment: "The Krusty Krab («Спанч Боб»)",
    text: "Также все другие известные генераторы Lorem Ipsum используют один и тот же текст, который они просто повторяют, пока не достигнут нужный объём. Это делает предлагаемый здесь генератор единственным настоящим Lorem Ipsum генератором. Он использует словарь из более чем 200 латинских слов, а также набор моделей предложений. В результате сгенерированный Lorem Ipsum выглядит правдоподобно",
    id: "thekrustykrab",
  },
  {
    zodiac: "Близнецы",
    name: "Охотники за приведениями",
    logo: "comps/ghost.svg",
    comment: "(«Охотники за приведениями»)",
    text: "Если вы регулярно пользуетесь этим сайтом и хотите быть уверенным в его дальнейшем постоянном функционировании, подумайте о небольшом пожертвовании, которое помогло бы оплатить его хостинг и трафик. Нет никаких минимальных сумм - любое пожертвование принимается с благодарностью. Вы можете щёлкнуть здесь чтобы перевести деньги через PayPal. Спасибо за вашу поддержку.",
    id: "ghostbusters",
  },
  {
    zodiac: "Рак",
    name: "Подиум",
    logo: "comps/runway.png",
    comment: "Подиум («Дьявол носит Prada»)",
    text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident",
    id: "runway",
  },
  {
    zodiac: "Лев",
    name: "6-ой Канал",
    logo: "comps/sixnews.png",
    comment: "6-ой Канал («Черепашки Ниндзя»)",
    text: "Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt.",
    id: "sixchannel",
  },
  {
    zodiac: "Дева",
    name: "Зима-Лето",
    logo: "comps/zimaletto.png",
    comment: "Зима-Лето («Не родись красивой»)",
    text: "But I must explain to you how all this mistaken idea of denouncing pleasure and praising pain was born and I will give you a complete account of the system, and expound the actual teachings of the great explorer of the truth, the master-builder of human happiness. No one rejects, dislikes, or avoids pleasure itself, because it is pleasure, but because those who do not know how to pursue pleasure rationally ",
    id: "zimaleto",
  },
  {
    zodiac: "Весы",
    name: "Red Apple",
    logo: "comps/redapple.svg",
    comment: "Сигареты Red Apple («Криминальное чтиво»)",
    text: "At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident, similique sunt in culpa qui officia deserunt mollitia animi, id est laborum et dolorum fuga. Et harum quidem rerum facilis est et expedita distinctio. Nam libero tempore, cum soluta nobis est eligendi",
    id: "redapple",
  },
  {
    zodiac: "Скорпион",
    name: "Ollivander's",
    logo: "comps/ollivanders.svg",
    comment:
      "Магазин волшебных палочек Ollivander's Wand Shop («Гарри Поттер и философский камень»)",
    text: 'Самый непредсказуемый и оттого такой притягательный! Если тебя захлёстывают эмоции, бываешь абсолютно несносным: стучишь кулаком по столу и иногда торопишься ставить точку там, где следовало бы поставить хотя бы запятую. Но сколько бы ты ни бил себя пяткой в грудь, доказывая что-то другим, самые близкие знают — внутри ты всё тот же, мягкий и тёплый. Поэтому ты всегда в их сердечках, в какой бы "обёртке" не предстал.',
    id: "ollivanders",
  },
  {
    zodiac: "Стрелец",
    name: "КООАМ или КАНИКТ",
    logo: "comps/choam.svg",
    comment: "КООАМ или КАНИКТ («Дюна»)",
    text: 'это текст-"рыба", часто используемый в печати и вэб-дизайне. Lorem Ipsum является стандартной "рыбой" для текстов на латинице с начала XVI века. В то время некий безымянный печатник создал большую коллекцию размеров и форм шрифтов, используя Lorem Ipsum для распечатки образцов. Lorem Ipsum не только успешно пережил без заметных изменений пять веков, но и перешагнул в электронный дизайн. ',
    id: "kooamorkanikt",
  },
  {
    zodiac: "Козерог",
    name: "Big Kahuna Burger",
    logo: "comps/kahuna.svg",
    comment: "Big Kahuna Burger («Бешенные псы»)",
    text: 'Давно выяснено, что при оценке дизайна и композиции читаемый текст мешает сосредоточиться. Lorem Ipsum используют потому, что тот обеспечивает более или менее стандартное заполнение шаблона, а также реальное распределение букв и пробелов в абзацах, которое не получается при простой дубликации "Здесь ваш текст.. Здесь ваш текст.. Здесь ваш текст.." Многие программы электронной вёрстки и редакторы HTML используют Lorem Ipsum',
    id: "bigkahunaburger",
  },
  {
    zodiac: "Водолей",
    name: "Гранд Будапешт",
    logo: "comps/budapest.svg",
    comment: "Отель «Гранд Будапешт»",
    text: 'Многие думают, что Lorem Ipsum - взятый с потолка псевдо-латинский набор слов, но это не совсем так. Его корни уходят в один фрагмент классической латыни 45 года н.э., то есть более двух тысячелетий назад. Ричард МакКлинток, профессор латыни из колледжа Hampden-Sydney, штат Вирджиния, взял одно из самых странных слов в Lorem Ipsum, "consectetur", и занялся его поисками в классической латинской литературе. В результате он нашёл',
    id: "grandbudapest",
  },
  {
    zodiac: "Рыбы",
    name: "Lacuna Inc.",
    logo: "comps/laguna.svg",
    comment:
      "Компания по стиранию воспоминаний Lacuna Inc. («Вечное сияние чистого разума»)",
    text: 'Этот трактат по теории этики был очень популярен в эпоху Возрождения. Первая строка Lorem Ipsum, "Lorem ipsum dolor sit amet..", происходит от одной из строк в разделе 1.10.32 Классический текст Lorem Ipsum, используемый с XVI века, приведён ниже. Также даны разделы 1.10.32 и 1.10.33 "de Finibus Bonorum et Malorum" Цицерона и их английский перевод, сделанный H. Rackham, 1914 год.',
    name: "lacunainc",
  },
];

export default comps;
